modLoader="javafml"
loaderVersion="31.2.31"
[[mods]]
modId="ironbackpacks" 
version="1"
displayName="Iron Backpacks"
# The description text for the mod (multi line!) (#mandatory)
description='''
Adds simple four different tiered backpacks.
'''
[[dependencies.ironbackpacks]]
    modId="forge"
    mandatory=true
    versionRange="31.2.31"
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.ironbackpacks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
